### PR TITLE
changes div to button element and removes size for primary example

### PR DESCRIPTION
**Pull request by gomezjuliana**
I left the focus outlines in because they help users identify where they are on a page :)

### CODE REVIEW

**Comment by hamstu** [comment]
Fantastic change for better a11y @gomezjuliana! Thank you 💯

**Comment by twanlass** [comment]
Nice one @gomezjuliana 🙌. Are you seeing dotted outlines for the focus state are are the [focus styles](https://github.com/bufferapp/ui/blob/9bd4aa37cdb1154dd0e0022d0d1f4fec29685bba/src/components/Button/style.js#L45) we added working (nice blue outline via a `box-shadow`) visible?

**Comment by gomezjuliana** [comment]
Hey @twanlass we're seeing the nice blue outlines 😁 https://cl.ly/7b358dd57193

I'll make sure to attach screenshots in future PRs!

By the way, @ivanaszuber I removed the aria-label as <button> elements are recognized by assistive technologies so it's not needed.  I also looked into using <div role=button>" and it works when there's a tab-index but it's generally recommended to use native elements so we can avoid tab-index conflicts :)

**Comment by ivanaszuber** [comment]
Amazing @gomezjuliana 😍 🌮 🎉 !!

**Comment by twanlass** [comment]
Awesome @gomezjuliana! Thanks for the video, too! 🌮🌮

**Pull request merged**
