### PR TITLE
[UI-247] Add a danger style variation for buttons

### PR DESCRIPTION
**Pull request by dace**
## Description

- Adds styles for a button type variation for danger (actions that are destructive)
- Passes down a `danger` prop type to adjust styles
- Passes down a `loading` prop in order to adjust styles based on if the state is loading
- Adds a danger button to the documentation

## Motivation and Context

Adds a danger style variation for buttons that involve a destructive action.

Task from Frontend Board: https://github.com/bufferapp/ui/issues/247
Figma design: https://www.figma.com/file/MgtrTHwQOczkZIhHmxVQ4lEN/BDS-Buttons?node-id=415%3A493

## Screenshots (if appropriate):

**Active**

Screen Shot 2020-10-26 at 12 05 45 PM

**Focus**

Screen Shot 2020-10-26 at 12 05 54 PM

**Loading**

Screen Recording 2020-10-26 at 12 11 PM

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style and guidelines of this project. 
- [ ] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
- [ ] I have updated the **CHANGELOG** document.
- [ ] I have added tests to cover my changes.
- [x] I have performed a self-review of my own code
- [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] All new and existing tests passed.
- [ ] I have performed the accessibility audit of my UI changes according to the accessibility doc. 
- [ ] [Buffer Engineers] Someone from the Design team reviewed and approved my changes
- [ ] [Buffer Engineers] I have notified the BDS team of my changes in the #proj-design-system Slack channel

### CODE REVIEW

**Comment by dace** [comment]
Hi @letsbleachthis, I noticed a few differences between what we have implemented and what is in the Figma designs (all small things). I just wanted to get your opinion on if these should be fixed or are ok to ship as is and we can update it later if needed. 

1. For focused buttons, the current border (box-shadow) is `3px`, but in the design it's `2px`.
2. For loading states, the animated spinning loader is currently a gray-ish color for buttons, but in the Figma design it's white.
3. For buttons, I noticed that we've been utilizing naming conventions found in other systems ("primary", "secondary", etc.). I've seen a few places reference button types that allow destructive actions to be of type "danger". I'm happy to use "negative" if we're good with that and the it is clear to the team.

**Comment by letsbleachthis** [comment]
Thanks for the ping @dace!

> 1. For focused buttons, the current border (box-shadow) is 3px, but in the design it's 2px.

We can stick with the current border implementation — (box-shadow) 3px — this is probably a case where our Figma files have gotten out of step with our implemented components, it would be best to keep consistent with our actual existing button styles.

> 2. For loading states, the animated spinning loader is currently a gray-ish color for buttons, but in the Figma design it's white.

Ah, you're right! This is an oversight on my part, I should have checked our current documentation. Let's go with gray for now, if that feels okay to you visually.

> 3. For buttons, I noticed that we've been utilizing naming conventions found in other systems ("primary", "secondary", etc.). I've seen a few places reference button types that allow destructive actions to be of type "danger". I'm happy to use "negative" if we're good with that and the it is clear to the team.

Good one! I think it makes sense to use a stronger word here. Primer, Pajamas, Carbon, and Atlassian's system all use "danger" to describe this, Polaris uses "destructive", which I also like. I'm flexible — I personally like "destructive" but "danger" seems quite prevalent, so it might make sense for us to use that!

**Review by hamstu — APPROVED** [review]
This is great @dace! LGTM 😄

**Review by ssvmvss — APPROVED** [review]
Thanks for your work on this @dace! ❤️

**Review by anafilipadealmeida — APPROVED** [review]
🚀 🚀

**Pull request merged**
