### PR TITLE
Add new Tag component

### PR DESCRIPTION
**Pull request by cmunozgar**
## Description
Adding a new Tag component. This basic component has been extracted from the shared-component `NavTag` in Publish

## Motivation and Context
The motivation behind this PR is to have a Tag component that will be used in a `DropdownMenu` component for the Canva integration.
image

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style and guidelines of this project. 
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [ ] I have updated the **CHANGELOG** document.
- [X] I have added tests to cover my changes.
- [X] I have performed a self-review of my own code
- [X] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] All new and existing tests passed.
- [ ] I have performed the accessibility audit of my UI changes according to the accessibility doc. 
- [ ] [Buffer Engineers] Someone from the Design team reviewed and approved my changes
- [ ] [Buffer Engineers] I have notified the BDS team of my changes in the #proj-design-system Slack channel

### CODE REVIEW

**Review by gmzjuliana — APPROVED** [review]
this looks great to me! thanks @cmunozgar

**Comment by letsbleachthis** [comment]
Thanks for taking the initiative to build this @cmunozgar! 🙌  I'm wondering if we might want to have a few Tag options or themes...there are a couple other places we're using something similar:
1. A counter for tabs within Publishing
2. An icon-only option to denote a paid/paywalled feature

Below is an image, and here are the components in Figma: https://www.figma.com/file/7aezdyyQXpZftsrOC8IgEg/UI-Building-Blocks?node-id=25%3A1921
CleanShot 2021-07-26 at 11 27 11@2x

**Comment by cmunozgar** [comment]
Thanks, @letsbleachthis for your comments. I have updated the documentation with the examples that you shared. Actually, I didn't need to add additional options to the component. Only by setting the colors was enough.

image

What I wonder is if want to have different sizes of tags (_small, normal, big_) 🤔

**Comment by letsbleachthis** [comment]
> Thanks, @letsbleachthis for your comments. I have updated the documentation with the examples that you shared. Actually, I didn't need to add additional options to the component. Just setting colors was enough. 😄
> 
> image
> 
> What I wonder is if want to have different sizes of tags (_small, normal, big_) 🤔

Hmm...I think we're okay with one standard size. It works well in a few scenarios: next to Paragraph or Label text, as well as in the Appshell (ex: "New" next to Engagement). I'm not sure I see a need for a larger one at the moment.

**Comment by letsbleachthis** [comment]
Ooh, one more thing @cmunozgar — it looks like on hover , the label inside the Tag is changing color. For the "New" tag, can we update it to stay white on hover?
CleanShot 2021-07-27 at 17 37 57

**Comment by cmunozgar** [comment]
Yes, @letsbleachthis, I tried to fix it in the Tag component itself, but the culprit is the Dropdown Menu component. I have raised another PR https://github.com/bufferapp/ui/pull/313 to fix the hover issue :)

**Pull request merged**
