### PR TITLE
Upgrade to styled-components v5

### PR DESCRIPTION
**Pull request by hamstu**
## Description

* 🔥  https://medium.com/styled-components/announcing-styled-components-v5-beast-mode-389747abd987

## Motivation and Context
Feels good to stay up to date and reap some nic perf. benefits too.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style and guidelines of this project. 
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the **CHANGELOG** document.
- [ ] I have added tests to cover my changes.
- [x] I have performed a self-review of my own code
- [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] All new and existing tests passed.
- [x] I have performed the accessibility audit of my UI changes according to the accessibility doc. 
- [ ] [Buffer Engineers] Someone from the Design team reviewed and approved my changes
- [ ] [Buffer Engineers] I have notified the BDS team of my changes in the #proj-design-system Slack channel

### CODE REVIEW

**Comment by gmzjuliana** [comment]
heya @hamstu thanks for keeping up updated! if we upgrade to v5 in BDS do all our apps have to upgrade as well?

**Comment by hamstu** [comment]
Thanks @msanroman and @gomezjuliana! Sorry for the late reply – I'll push out a beta release of this next week! 👌 💯

**Comment by karelm** [comment]
Hey @hamstu, could we get this upgrade moved forward at all? I see that version 5 of styled components is backwards compatible with 4 and has no breaking changes (according to the documentation), so I'd love to be able to push forward with this. I know in publish we are already using version 5, and having 1 version across projects would be really good. I'd possibly also suggest we move forward to using a version string with the hat `^` character to allow us to continually upgrade inside a version, whats your thoughts on this?

**Comment by djfarrelly** [comment]
I was planning to write up a new issue suggesting we move `styled-components` to `peerDependencies` to save our apps' webpack config to have tree shaking configured. In the engage bundle we're seeing the package included twice and it's added an extra 29k! This is a great upgrade, but also a great change to peer deps @hamstu!

**Pull request merged**
