### PR TITLE
fix icon script and rebuild

### PR DESCRIPTION
**Pull request by hamstu**
## Description
- fix icon script
- generate new icons: Coupon, Card and Spam
- remove padding in Simple Modal
- fix Switch propType for id: change from bool to string

## Motivation and Context
We're not sure what happened with the icon generation script. It might've been a small change that James recently did or Figma might've changed the API recently. Regardless, the script is now fixed but since we moved to actually running prettier on the icons, all the icon files generated changes. Tested locally in BDS and app-shell, there seems to be no regressions. 

The padding on the simple modal was removed so the children can handle their own padding according to styles for the Plan Selector

The id on the Switch was changed from bool to string as ids are usually strings

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style and guidelines of this project. 
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have updated the **CHANGELOG** document.
- [x] I have added tests to cover my changes.
- [x] I have performed a self-review of my own code
- [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] All new and existing tests passed.
- [x] I have performed the accessibility audit of my UI changes according to the accessibility doc. 
- [ ] [Buffer Engineers] Someone from the Design team reviewed and approved my changes
- [ ] [Buffer Engineers] I have notified the BDS team of my changes in the #proj-design-system Slack channel

### CODE REVIEW

**Comment by gmzjuliana** [comment]
@hamstu thanks for fixing the script! I added the other changes I needed, if you're keen to review since I can't tag ya 😅

**Comment by hamstu** [comment]
LGTM @gmzjuliana!

**Review by albennett — APPROVED** [review]
Thanks for fixing the script. What exactly was happening? 🤔  
Funny enough, I started to add the switch proptype change to this [PR](https://github.com/bufferapp/ui/pull/284). Thanks for including it!

**Comment by hamstu** [comment]
@albennett We have a part of the script that converts the SVG we get from the Figma API to React (JSX) syntax. E.g., `<svg><path fill-rule="..."></svg>` becomes `<svg><path fillRule="..."></svg>` but the library doing that had a change where it started [wrapping the output as a full React component](https://github.com/balajmarius/svg2jsx/blob/e44a3717866cafd8b1bc64594576f635e630399e/packages/transform/lib/formatter.js#L21-L30) and that was throwing our own icon generation script since [it already does that](https://github.com/bufferapp/ui/blob/0c6337f6707e83f97d3e2ad5d81c2221a25717c9/scripts/generateIconComponents.js#L152-L170).

So yeah, I fixed the code to clean/remove the wrapper we get from `svg2jsx` (since it's unfortunately not an option in it's API) and then went ahead and added prettier formatting to all the generated icon files.

So the diff is because of:
1) 3 new icons
2) Prettier-ed new + existing icons (changed a lot of indentation)
3) Existing Icon changes; but not visually, just subtle changes in the SVG paths from Figma's API 🤷🏻

**Pull request merged**
