### PR TITLE
Replace usage and reference of npm with yarn

### PR DESCRIPTION
**Pull request by guldenmw**
## Description

- Remove reference of npm from all documentation. 
- Replace npm calls with yarn calls in package.json
- Remove `package-lock.json`

## Motivation and Context

We're simultaneously maintaining a package-lock.json and a yarn.lock and our documentation is unclear on which we prefer.
This PR removes npm in favour of using yarn.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style and guidelines of this project. 
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have updated the **CHANGELOG** document.
- [ ] I have added tests to cover my changes.
- [ ] I have performed a self-review of my own code
- [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] All new and existing tests passed.
- [ ] I have performed the accessibility audit of my UI changes according to the accessibility doc. 
- [ ] [Buffer Engineers] Someone from the Design team reviewed and approved my changes
- [ ] [Buffer Engineers] I have notified the BDS team of my changes in the #proj-design-system Slack channel

### CODE REVIEW

**Review by gmzjuliana — CHANGES_REQUESTED** [review]
hey @guldenmw thanks for working on this! I noticed the test fail, would you be up for checking if we need to tweak anything else in travis?

**Review by gmzjuliana — APPROVED** [review]
almost!! almost!! jajajaja @guldenmw this is great, just fix a couple conflicts and it's good to go. Feel free to merge and deploy a new version once you've done that :shipit:

**Review by MayaUribe — APPROVED** [review]
@guldenmw such a useful change! Thank you so much for these changes! 🤩

**Review by federicoweber — APPROVED** [review]
Thanks @guldenmw 🥇

**Pull request merged**
