### PR TITLE
Show more relevant search results first

### PR DESCRIPTION
**Pull request by mickmahady**
## Description
When using the search input, display first the results that start with the searched expression, and only after show the other results that contain the searched expression.

Relates to #242 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style and guidelines of this project. 
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the **CHANGELOG** document. (will update before merging)
- [x] I have added tests to cover my changes.
- [x] I have performed a self-review of my own code
- [x] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] All new and existing tests passed.
- [ ] I have performed the accessibility audit of my UI changes according to the accessibility doc. 
- [ ] [Buffer Engineers] Someone from the Design team reviewed and approved my changes
- [ ] [Buffer Engineers] I have notified the BDS team of my changes in the #proj-design-system Slack channel

### CODE REVIEW

**Comment by anafilipadealmeida** [comment]
Hey @mickmahady, I'm curious, does it end up working without replacing `@babel/react` by `@babel/preset-react`?

**Comment by mickmahady** [comment]
Seems to work well for me, @anafilipadealmeida! Just to be sure, I've tried it again locally and it seems to do the trick. It was fine when testing the Beta version in Publish too. I've yet to come across the error you showed me, without changing the presets. I'm wondering if you could pull this branch and see if you can still get the error to occur? I haven't been able to replicate it :sweat_smile:

**Comment by anafilipadealmeida** [comment]
hey @msanroman, I could use another pair of eyes in this one! I pull the branch and do `npm run start`, go to http://localhost:3000/#/ui/select and I'm not able to see the page, only errors. It's fixed by changing "@babel/react" to "@babel/preset-react" in package.json babel presets. Would you mind confirming if you see the same?

**Review by anafilipadealmeida — APPROVED** [review]
Hey @mickmahady, Hamish confirmed it's looking good for him, so feel free to deploy this ❤️

**Pull request merged**
