### PR TITLE
Adding new color values

### PR DESCRIPTION
**Pull request by letsbleachthis**
## Description

Adding new Lightest color values as well as filling in existing Dark, Darker, Light, Lighter values that existed in Figma, but not code. Design documentation in Figma and Notion has already been updated.

## Screenshots (if appropriate):
CleanShot 2021-06-09 at 18 47 03

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style and guidelines of this project. 
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the **CHANGELOG** document.
- [ ] I have added tests to cover my changes.
- [ ] I have performed a self-review of my own code
- [ ] I have tested my changes/additions in the latest Chrome, Firefox, and Safari.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] All new and existing tests passed.
- [ ] I have performed the accessibility audit of my UI changes according to the accessibility doc. 
- [ ] [Buffer Engineers] Someone from the Design team reviewed and approved my changes
- [ ] [Buffer Engineers] I have notified the BDS team of my changes in the #proj-design-system Slack channel

### CODE REVIEW

**Comment by letsbleachthis** [comment]
Hey @federicoweber @dace 👋 — along with adding the new Lightest color values, I added the remaining Dark-Lighter values from our color palette. You'll notice that I updated the existing values for `redLightest` and `orangeDark` as well. I went ahead and checked to see where we were using these values:
- `redLighter` is used for errored inputs (https://cln.sh/yAH0fY) and I checked to make sure this still meets a11y standards (it passes AA) 
- `orangeDark` is used for banners (https://cln.sh/nMSQXb) and the change meant we failed AA standards, so included in this PR are commits for updating the banner text and button to use `orangeDarker` instead. That passes AA standard 👍 

Please let me know if any of this looks off!

**Review by federicoweber — APPROVED** [review]
This is looking great @letsbleachthis 🙌 .
I think the build is failing because of the branch name, but I tested it locally and it all looks fine.

**Comment by letsbleachthis** [comment]
> This is looking great @letsbleachthis 🙌 .
> I think the build is failing because of the branch name, but I tested it locally and it all looks fine.

Thanks @federicoweber! Any idea what about the branch name could be causing this? I probably should have checked for any obvious conventions with existing branches before creating a new one.

**Comment by federicoweber** [comment]
> Any idea what about the branch name could be causing this? I probably should have checked for any obvious conventions with existing branches before creating a new one.

We have a soft convention to use `task/branch-name` or `fix/branch-name`, I think the uppercase might e throwing this off but it's kind of strange really, it looks like it's building the container but failing running jest, and that should not happen.

Actually let me take a look, I still don't think it's related to your changes, but it's odd.

**Comment by federicoweber** [comment]
Not branch name related, just tested squashing all your changes in a new branch still same issue https://github.com/bufferapp/ui/compare/task/new-colours?expand=1

**Comment by federicoweber** [comment]
@letsbleachthis I git this working, was an issue with `jest-environment-jsdom`, feel free to merge

**Pull request merged**
