### PR TITLE
adds prop to allow for full width buttons

### PR DESCRIPTION
**Pull request by gomezjuliana**
This is almost ready, I'm just having a bit of a hard time getting the documentation site looking nice: https://cl.ly/da796b43ef23

I have a hunch that we need to add a conditional via a prop to `src/documentation/app/layout/content/components/Example.jsx` in `ExampleWrapper` on line 28 but I have tangled myself up on where to add the prop.. is it in that same file or maybe in `src/documentation/app/layout/content/Component.jsx` ?? Hehe 🤨Would love some advice if you folks have any, please and thanks 🙏

### CODE REVIEW

**Comment by twanlass** [comment]
@gomezjuliana one suggestion for the doc site – I might make the labels block level elements so that that buttons are pushed to the next row and left aligned (the block level button will then look much nicer): 

image

**Comment by hamstu** [comment]
Came here to say what @twanlass said! I think keeping things block + left aligned would serve us well. 👍

**Comment by gomezjuliana** [comment]
Awesome! Added this in: 
https://cl.ly/07d160027783

This does however, raise an issue with the selects:
https://cl.ly/b931cc31242f

But @ivanaszuber and I have a sync in a couple minutes, I'll touch base with her on this!

Thanks @twanlass and @hamstu

**Comment by ivanaszuber** [comment]
Great stuff @gomezjuliana ! Let me know in case our solution for select doesn't work, happy to help there! Otherwise, feels great to push a new version of the package and try this out in Reply 😍 !

**Pull request merged**
